branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true
  - name: master

verifyConditions:
  - "@semantic-release/github"
  - "@semantic-release/npm"
generateNotes: []
prepare: []
publish: []
success: []
fail: []
