branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true
  - name: master

plugins:
  - "@semantic-release/github"
  - "@semantic-release/npm"
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - plugin: "@semantic-release/git"
    assets: ["package.json"]
    message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
generateNotes: []
prepare: []
publish: []
success: []
fail: []
