branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true
  - name: master

plugins:
  - "@semantic-release/github"
  - "@semantic-release/npm"
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
generateNotes: []
prepare: []
publish: []
success: []
fail: []
